### ISSUE TITLE
Migration to OoTR v2 API

### ISSUE THREAD

**Issue by TreZc0** [christianlegge/cojiro#4]
Heya, i noticed you are still running on OoTR v1 API.
We want to sunset this, as you seem to be its only user.

Can you reach out to me on Discord to talk it through and get an updated API key?
API v2 docs can be found here: https://ootrandomizer.com/api/docs

**Comment by christianlegge** [comment]
The migration to v2 has been completed, the live app now only hits v2 endpoints.
